version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/lmp-backend:${BUILD_NUMBER}
    container_name: lmp-backend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__LMPConnect=${DB_CONNECTION_STRING}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - SmtpSettings__Host=${SMTP_HOST}
      - SmtpSettings__Port=${SMTP_PORT}
      - SmtpSettings__Username=${SMTP_USERNAME}
      - SmtpSettings__Password=${SMTP_PASSWORD}
    restart: unless-stopped

  frontend:
    image: ${DOCKERHUB_USERNAME}/lmp-frontend:${BUILD_NUMBER}
    container_name: lmp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
